version: "3"
services:
  tests:
    build: .
    volumes: 
      - $PWD:/opt/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - "TIMEZONE=UTC"